name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Create Custom Usermod
      run: |
        mkdir -p /tmp/WLEDtemp/usermods
        cat > /tmp/WLEDtemp/usermods/usermod_zalgiris_effects.h << 'EOL'
        #pragma once
        #include "wled.h"
        // ... paste the entire usermod code here ...
        EOL

    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/Aircoookie/WLED/archive/refs/heads/main.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install

        # Copy custom usermod
        cp /tmp/WLEDtemp/usermods/usermod_zalgiris_effects.h wled00/

        # Update platformio.ini
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32dev' >>platformio.ini
        echo 'build_flags = ${env:esp32dev.build_flags}' >>platformio.ini
        echo '  -D USERMOD_PING_PONG_CLOCK' >>platformio.ini
        echo '  -D USERMOD_WORDCLOCK' >>platformio.ini
        echo '  -D USERMOD_ANALOG_CLOCK' >>platformio.ini
        echo '  -D USERMOD_ZALGIRIS' >>platformio.ini
        echo 'build_unflags = -D WLED_RELEASE_NAME' >>platformio.ini

        # Update usermods_list.cpp
        echo '#include "usermod_zalgiris_effects.h"' >> wled00/usermods_list.cpp
        echo 'void registerUsermods() {' >> wled00/usermods_list.cpp
        echo '  usermods.add(new ZalgirisEffects());' >> wled00/usermods_list.cpp
        echo '}' >> wled00/usermods_list.cpp

        pio run -e custom_build || pio run -e custom_build

    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt

    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Add Zalgiris Effects Custom Build"
        git push origin main
